---
# ansible_host: openafs.mit.edu
ansible_user: buildbot
buildbot_project: openafs
buildbot_master_have_sudo: no
buildbot_master_install: no
buildbot_master_basedir: "/home/buildbot/buildbot/master"
buildbot_master_gerrit_ident: gerrit
buildbot_master_gerrit_hostkey: gerrit.hostkey
buildbot_master_config_files:
  - "{{ playbook_dir }}/files/master.cfg"
  - "{{ playbook_dir }}/files/settings.py"
  - "{{ playbook_dir }}/files/forcegerritbuild.py"
  - "{{ playbook_dir }}/files/email_templates.py"
  - "{{ playbook_dir }}/files/passwords.ini"

afsbotcfg_title: 'The OpenAFS Buildbot Master'
afsbotcfg_url: "https://buildbot.openafs.org/"
afsbotcfg_www_port: 8010
