---
# ansible_host: openafs-prod-app-1.mit.edu
ansible_user: buildbot
buildbot_project: openafs
buildbot_master_have_sudo: no
buildbot_master_install: no
buildbot_master_sqlalchemy_version: '==1.3.17'
buildbot_master_buildbot_version: '==2.8.2'
buildbot_master_python: "/opt/rh/rh-python36/root/usr/bin/python3.6"
buildbot_master_basedir: "/home/buildbot/master/openafs"
buildbot_master_url: "https://buildbot.openafs.org/"
buildbot_master_www_port: 8011
buildbot_master_gerrit_ident: gerrit
buildbot_master_gerrit_hostkey: gerrit.hostkey
buildbot_master_config_files:
  - master.cfg
  - forcegerritbuild.py
  - email_templates.py
  - passwords.ini
