---
- name: "Variable checks"
  assert:
    that:
      - buildbot_project is defined

- name: "Install required packages"
  become: yes
  yum:
    state: present
    name:
      - python3
      - make
      - gcc
      - patch
  when: have_sudo | bool
  tags: root

- name: "Create local directories"
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ ansible_user_dir }}/.ssh"
      mode: "0700"
    - path: "{{ ansible_user_dir }}/.local/bin"
      mode: "0755"
    - path: "{{ buildbot_master_venv }}"
      mode: "0755"
    - path: "{{ buildbot_master_basedir }}"
      mode: "0755"

- name: "Install buildbot"
  pip:
    name: 'buildbot[bundle]'
    virtualenv: "{{ buildbot_master_venv }}"
    virtualenv_command: "{{ buildbot_master_python }} -m venv"
  when: buildbot_install_master | default('yes') | bool

# Apply bug fix. For more information see:
# - https://github.com/buildbot/buildbot/issues/5190
# - https://github.com/buildbot/buildbot/pull/5219/commits
- name: "Apply patches"
  patch:
    src: buildbot-issue-5190.patch
    # todo: find path to site-packages?
    basedir: "{{ buildbot_master_venv }}/lib/python3.6/site-packages/buildbot"
  tags: patch
  when: buildbot_install_master | default('yes') | bool

- name: "Create symlink to buildbot command"
  file:
    state: link
    src: "{{ buildbot_master_venv }}/bin/buildbot"
    path: "{{ buildbot_bin }}"
  when: buildbot_install_master | default('yes') | bool

- name: "Create master"
  command:
    cmd: "{{ buildbot_bin }} create-master {{ buildbot_master_basedir }}"
    creates: "{{ buildbot_master_basedir }}/buildbot.tac"

- name: "Remove sample configuration"
  file:
    path: "{{ buildbot_master_basedir }}/master.cfg.sample"
    state: absent

- name: "Install master configuration"
  copy:
    src: "{{ item.src }}"
    dest: "{{ buildbot_master_basedir }}/{{ item.src | basename }}"
    decrypt: "{{ item.decrypt }}"
  loop: "{{ buildbot_master_config_files }}"
  when: buildbot_master_config_files is defined
  notify: "reload buildbot master"

- name: "Install buildbot master local settings"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ buildbot_master_basedir }}/{{ item.src | basename }}"
    decrypt: "{{ item.decrypt }}"
  loop:
    "{{ buildbot_master_config_templates }}"
  when: buildbot_master_config_templates is defined
  notify: "reload buildbot master"

- name: "Check new master configuration"
  command:
    cmd: "{{ buildbot_bin }} checkconfig"
    chdir: "{{ buildbot_master_basedir }}"
  changed_when: false

- name: "Install sudoers file"
  become: yes
  copy:
    src: "10-buildbot.sudoers"
    dest: "/etc/sudoers.d/10-buildbot"
    mode: "0440"
    owner: root
    group: root
  when: have_sudo | bool
  tags: root

- name: "Install systemd unit file"
  become: yes
  template:
    src: buildbot.service.j2
    dest: "/etc/systemd/system/buildbot.service"
  when: have_sudo | bool
  tags: root

- name: "Starting buildbot"
  become: yes
  systemd:
    name: buildbot
    daemon_reload: yes
    enabled: yes
    state: "{{ buildbot_master_restart | ternary('restarted', 'started') }}"
  register: buildbot_master_start_results
  when: have_sudo | bool
  tags: root
